Miniconda 4.12.0
conda/conda-docs pull request #788
Opened 2022-05-16 21:25 UTC by pseudoyim

Update links and add hashes for Miniconda v4.12.0.

2022-05-16 21:31 UTC, kathatherine approved these changes
LGTM

2022-05-16 21:31 UTC, kathatherine commented on docs/source/miniconda.rst
> +   ,`Miniconda3 Linux-aarch64 64-bit <https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh>`_,``5f4f865812101fdc747cea5b820806f678bb50fe0a61f19dc8aa369c52c4e513``
So are the hashes on the latest installer not supposed to match the very first installers in the miniconda_hashes list? Like the hash for Linux-aarch64 is 5f4f865812101fdc747cea5b820806f678bb50fe0a61f19dc8aa369c52c4e513 here, but it's 47affd9577889f80197aadbdf1198b04a41528421aaf0ec1f28b04a50b9f3ab8 in miniconda_hashes. Still different installers?

2022-05-16 21:31 UTC, kathatherine commented on docs/source/miniconda.rst
> +   ,`Miniconda3 Linux-aarch64 64-bit <https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh>`_,``5f4f865812101fdc747cea5b820806f678bb50fe0a61f19dc8aa369c52c4e513``
Oh wait, I found the same hash a bit further down the list with the 3.9 installers. I see now that that other hash was for 3.7.

2022-05-18 13:59 UTC, csoja requested changes

2022-05-18 13:59 UTC, csoja commented on docs/source/miniconda.rst
> +   Linux,`Miniconda3 Linux 64-bit <https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh>`_,``78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689``
I'm not seeing the latest .pkg link for macOSX-arm64 - only the .sh link. Other than that, this all LGTM.

2022-05-18 14:33 UTC, csoja commented on docs/source/miniconda.rst
> +   Linux,`Miniconda3 Linux 64-bit <https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh>`_,``78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689``
Thanks for adding it!

2022-05-18 14:34 UTC, csoja approved these changes
LGTM Thank you for updating the conda version for the latest as well!

2022-05-18 14:35 UTC, skalburgi approved these changes
LGTM

2022-05-18 14:50 UTC, jezdez commented
@conda-bot check

2022-05-18 14:51 UTC, jezdez approved these changes

2022-05-18 16:58 UTC, merged

2022-05-19 17:13 UTC, jezdez commented
Fixes #775.