875 rework miniconda docs
conda/conda-docs pull request #876
Opened 2023-07-28 22:01 UTC by kathatherine

### Description

This PR updates the Miniconda docs a great deal. It moves most information to their own pages, to clean up the main page, and adds some quick command line install commands.

I wanted to go ahead and get the work as it stands pushed, but I still want to play with it some more. Ideas include:

- Put latest installer links back on main page, but put the OS-specific tables in drop downs to keep things cleaner? This will require some jinja work that I don't have a great understanding of, but can get help with.
- Improve the more involved installer instructions. Those are not actually done yet on all OS tabs. I'll mark it with a comment.
- System requirements could also not have to go on its own page. They could be put in a dropdown labeled System requirements on the front page.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] ~Add / update outdated documentation?~

2023-07-28 22:02 UTC, kathatherine commented on docs/source/miniconda-install.rst
> +    .. tab-item:: Linux
Haven't finished the Linux bit yet.

2023-08-03 20:57 UTC, kathatherine commented
@marcoesters This is ready for you when you're ready.

2023-08-21 18:54 UTC, kathatherine commented
I think the current pre-commit issue can be fixed with merging main once https://github.com/conda/conda-docs/pull/877 is merged in.

2023-08-21 20:21 UTC, marcoesters submitted a review, later dismissed

2023-08-22 01:45 UTC, kathatherine commented
pre-commit.ci autofix

2023-08-22 07:32 UTC, jezdez requested changes
We need to split the miniconda docs into a separate repo that we publish like the other projects in ReadTheDocs. It's uncanny how an Anaconda product (miniconda) is intermingled with the conda Open Source docs preventing us from decoupling the work on conda projects.

2023-08-22 16:03 UTC, kathatherine commented
@jezdez Yes, I figured we'd do this work and then split it off from the conda-docs repo in a different PR. But if you want to do it differently, we should discuss that.

2023-08-22 16:11 UTC, marcoesters commented
> We need to split the miniconda docs into a separate repo that we publish like the other projects in ReadTheDocs. It's uncanny how an Anaconda product (miniconda) is intermingled with the conda Open Source docs preventing us from decoupling the work on conda projects.

While I agree with you, I think this is out of scope for this PR.

I suggest we migrate this into a separate repo after this PR is merged.

2023-08-22 17:06 UTC, jezdez commented
> > We need to split the miniconda docs into a separate repo that we publish like the other projects in ReadTheDocs. It's uncanny how an Anaconda product (miniconda) is intermingled with the conda Open Source docs preventing us from decoupling the work on conda projects.
> 
> While I agree with you, I think this is out of scope for this PR.
> 
> I suggest we migrate this into a separate repo after this PR is merged.

Sounds good to me, just wanted to make sure we're clear on the next steps and don't duplicate efforts.

2023-08-22 17:06 UTC, jezdez approved these changes

2023-08-22 17:11 UTC, merged