Add goat counter to docs site
conda/conda-docs pull request #914
Opened 2023-12-01 14:26 UTC by travishathaway

Fixes: https://github.com/conda/conda-docs/issues/905

2023-12-04 17:04 UTC, jezdez requested changes

2023-12-04 17:04 UTC, jezdez commented on docs/source/_templates/layout.html
> +        async src="//gc.zgo.at/count.js"></script>
Just like https://github.com/conda/conda-build/pull/5093#discussion_r1413564562, we should host `count.js` ourselves

2023-12-06 10:02 UTC, jezdez submitted a review, later dismissed

2023-12-06 15:10 UTC, beeankha approved these changes

2023-12-06 17:07 UTC, beeankha approved these changes

2023-12-06 17:22 UTC, merged